language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "node"

os:
  - "linux"
  - "osx"
  # - "windows"

sudo:     false

install:
  - "npm install && \
    npm install -g mocha@^5.2.0 && \
    npm install -g nyc@^13.1.0"

script:
  - npm run lint
  - npm test
